### ISSUE TITLE
Add to flow-typed

### ISSUE THREAD

**Issue by edorivai** [christophehurpeaudeprecated/koa-flow-declarations#1]
Just curious; is there any particular reason why these declarations have not been added to https://github.com/flowtype/flow-typed ?

**Comment by christophehurpeau** [comment]
It seems they exists : https://github.com/flowtype/flow-typed/blob/master/definitions/npm/koa_v2.x.x/flow_v0.38.x-v0.38.x/koa_v2.x.x.js

I used [babel-plugin-tcomb](https://github.com/gcanti/babel-plugin-tcomb) at the time and wasn't aware of flow-types
I don't use this anymore :)

**Comment by edorivai** [comment]
Aha, thanks! I came here because `flow-typed install` only installed the automatically generated stub (which is not very useful). It seems that the definitions you're referring to are for an older version of flow.

It needs to be upgraded to 0.44: https://github.com/flowtype/flow-typed/issues/790

Just leaving this info for future googlers :).
